// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace accessVityzReports.Models
{
    public partial class Reports
    {
        public Reports()
        {
            UsersReports = new HashSet<UsersReports>();
        }

        public Guid RptId { get; set; }
        public string RptName { get; set; }

        public virtual ICollection<UsersReports> UsersReports { get; set; }
    }
}