// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace accessVityzReports.Models
{
    public partial class UsersReports
    {
        public Guid Id { get; set; }
        public string UsrLogin { get; set; }
        public Guid RptId { get; set; }

        public virtual Reports Rpt { get; set; }
    }
}